server:
 port: 8081
 servlet:
  context-path: /registration
   
spring:
 application:
  name: registration-service
 datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/messanger
  username:
  password:
 jpa:
  hibernate:
   ddl-auto: validate
  database: postgresql
  show-sql: true
  properties:
   hibernate:
    format-sql: true
 kafka:
  bootstrap-servers: localhost:9093
  consumer:
   group-id: registration-group
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer           