server:
  port: 8082
  servlet:
    context-path: /communication

spring:
  application:
    name: communication-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/messanger
    username: postgres
    password: Sber2022++ST
    jpa:
      hibernate:
        ddl-auto: validate
      database: postgresql
      show-sql: true
      properties:
        hibernate:
          format-sql: true
  data:
    mongodb:
      url: mongodb://localhost:27017/messanger
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: communication-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer